### ISSUE TITLE
Error on server restart: Plugin attempts to register task while disabled

### ISSUE THREAD

**Issue by servicomcr** [Artillex-Studios/AxGraves#22]
Al reiniciar el servidor, el plugin AxGraves v1.13.2 lanza una excepción `IllegalPluginAccessException`. Esto ocurre porque el plugin intenta registrar una tarea en el programador de tareas de Bukkit (`CraftScheduler`) mientras el plugin ya ha sido deshabilitado.
///

Upon restarting the server, the AxGraves plugin v1.13.2 throws an `IllegalPluginAccessException`. This happens because the plugin attempts to register a task in the Bukkit scheduler (`CraftScheduler`) while the plugin is already disabled.

[17:52:22 INFO]: [AxGraves] Disabling AxGraves v1.13.2
[17:52:22 ERROR]: Error occurred while disabling AxGraves v1.13.2
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.validate(CraftScheduler.java:539) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:219) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:215) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:179) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTask(CraftScheduler.java:148) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at AxGraves-1.13.2.jar/com.artillexstudios.axgraves.libs.axapi.scheduler.impl.BukkitScheduler.runAt(BukkitScheduler.java:81) ~[AxGraves-1.13.2.jar:?]
        at AxGraves-1.13.2.jar/com.artillexstudios.axgraves.grave.Grave.remove(Grave.java:248) ~[AxGraves-1.13.2.jar:?]
        at AxGraves-1.13.2.jar/com.artillexstudios.axgraves.AxGraves.disable(AxGraves.java:76) ~[AxGraves-1.13.2.jar:?]
        at AxGraves-1.13.2.jar/com.artillexstudios.axgraves.libs.axapi.AxPlugin.onDisable(AxPlugin.java:156) ~[AxGraves-1.13.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:623) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1057) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:883) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1388) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by BenceX100** [comment]
This should be fixed in the latest version!

**Comment by servicomcr** [comment]
Aun me sale el mismo error deberías de revisar 

[17:49:06 INFO]: [AxGraves] Disabling AxGraves v1.13.5
[17:49:06 ERROR]: Error occurred while disabling AxGraves v1.13.5
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.validate(CraftScheduler.java:539) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:219) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:215) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:179) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTask(CraftScheduler.java:148) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at AxGraves-1.13.5 (1).jar/com.artillexstudios.axgraves.libs.axapi.scheduler.impl.BukkitScheduler.runAt(BukkitScheduler.java:81) ~[AxGraves-1.13.5 (1).jar:?]
        at AxGraves-1.13.5 (1).jar/com.artillexstudios.axgraves.grave.Grave.remove(Grave.java:248) ~[AxGraves-1.13.5 (1).jar:?]
        at AxGraves-1.13.5 (1).jar/com.artillexstudios.axgraves.AxGraves.disable(AxGraves.java:76) ~[AxGraves-1.13.5 (1).jar:?]
        at AxGraves-1.13.5 (1).jar/com.artillexstudios.axgraves.libs.axapi.AxPlugin.onDisable(AxPlugin.java:156) ~[AxGraves-1.13.5 (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:623) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1057) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:883) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1388) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by servicomcr** [comment]
[02:30:30 INFO]: [AxGraves] Disabling AxGraves v1.13.5
[02:30:30 ERROR]: Error occurred while disabling AxGraves v1.13.5
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.validate(CraftScheduler.java:539) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:219) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:215) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:179) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTask(CraftScheduler.java:148) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at AxGraves-1.13.5 (1).jar/com.artillexstudios.axgraves.libs.axapi.scheduler.impl.BukkitScheduler.runAt(BukkitScheduler.java:81) ~[AxGraves-1.13.5 (1).jar:?]
        at AxGraves-1.13.5 (1).jar/com.artillexstudios.axgraves.grave.Grave.remove(Grave.java:248) ~[AxGraves-1.13.5 (1).jar:?]
        at AxGraves-1.13.5 (1).jar/com.artillexstudios.axgraves.AxGraves.disable(AxGraves.java:76) ~[AxGraves-1.13.5 (1).jar:?]
        at AxGraves-1.13.5 (1).jar/com.artillexstudios.axgraves.libs.axapi.AxPlugin.onDisable(AxPlugin.java:156) ~[AxGraves-1.13.5 (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:623) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1057) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:883) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1388) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by BenceX100** [comment]
The 1.13.6 version should solve this!
