### ISSUE TITLE
Error occurred while enabling AxGraves v1.14.0 

### ISSUE THREAD

**Issue by servicomcr** [Artillex-Studios/AxGraves#26]
[06:13:39] [Server thread/ERROR]: Error occurred while enabling AxGraves v1.14.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getEnvironment()" because the return value of "org.bukkit.Location.getWorld()" is null
	at AxGraves-1.14.0.jar/com.artillexstudios.axgraves.grave.Grave.<init>(Grave.java:66) ~[AxGraves-1.14.0.jar:?]
	at AxGraves-1.14.0.jar/com.artillexstudios.axgraves.grave.SpawnedGraves.loadFromFile(SpawnedGraves.java:94) ~[AxGraves-1.14.0.jar:?]
	at AxGraves-1.14.0.jar/com.artillexstudios.axgraves.AxGraves.enable(AxGraves.java:55) ~[AxGraves-1.14.0.jar:?]
	at AxGraves-1.14.0.jar/com.artillexstudios.axgraves.libs.axapi.AxPlugin.onEnable(AxPlugin.java:111) ~[AxGraves-1.14.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[06:13:39] [Server thread/INFO]: [AxGraves] Disabling AxGraves v1.14.0
[06:13:39] [Server thread/ERROR]: Error occurred while disabling AxGraves v1.14.0
java.lang.NullPointerException: Cannot invoke "com.artillexstudios.axgraves.libs.axapi.packetentity.PacketEntity.remove()" because the return value of "com.artillexstudios.axgraves.grave.Grave.getEntity()" is null
	at AxGraves-1.14.0.jar/com.artillexstudios.axgraves.AxGraves.disable(AxGraves.java:68) ~[AxGraves-1.14.0.jar:?]
	at AxGraves-1.14.0.jar/com.artillexstudios.axgraves.libs.axapi.AxPlugin.onDisable(AxPlugin.java:156) ~[AxGraves-1.14.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by tommasov03** [comment]
Same error with the 1.14.5 version

[10:38:50 INFO]: [AxGraves] Disabling AxGraves v1.14.5
[10:38:50 ERROR]: Error occurred while disabling AxGraves v1.14.5
java.lang.NullPointerException: Cannot invoke "com.artillexstudios.axgraves.libs.axapi.packetentity.PacketEntity.remove()" because the return value of "com.artillexstudios.axgraves.grave.Grave.getEntity()" is null
        at AxGraves-1.14.5.jar/com.artillexstudios.axgraves.AxGraves.disable(AxGraves.java:70) ~[AxGraves-1.14.5.jar:?]
        at AxGraves-1.14.5.jar/com.artillexstudios.axgraves.libs.axapi.AxPlugin.onDisable(AxPlugin.java:131) ~[AxGraves-1.14.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[universe-1.21.1.jar:1.21.1-077c3a9]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:241) ~[universe-1.21.1.jar:1.21.1-077c3a9]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:162) ~[universe-1.21.1.jar:1.21.1-077c3a9]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[universe-1.21.1.jar:1.21.1-077c3a9]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[universe-1.21.1.jar:1.21.1-077c3a9]
        at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:620) ~[universe-1.21.1.jar:1.21.1-077c3a9]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1051) ~[universe-1.21.1.jar:1.21.1-077c3a9]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:863) ~[universe-1.21.1.jar:1.21.1-077c3a9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1365) ~[universe-1.21.1.jar:1.21.1-077c3a9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[universe-1.21.1.jar:1.21.1-077c3a9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by BenceX100** [comment]
Should be fixed in the latest version
