### ISSUE TITLE
java.io.FileNotFoundException: plugins/AxGraves/data.json (No such file or directory)

### ISSUE THREAD

**Issue by servicomcr** [Artillex-Studios/AxGraves#27]
The interesting thing is that the file is generated correctly

![image](https://github.com/user-attachments/assets/61acc820-bb5d-4502-b98c-aec1410c238c)

[11:01:15 WARN]: java.io.FileNotFoundException: plugins/AxGraves/data.json (No such file or directory)
[11:01:15 WARN]:        at java.base/java.io.FileInputStream.open0(Native Method)
[11:01:15 WARN]:        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
[11:01:15 WARN]:        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
[11:01:15 WARN]:        at java.base/java.io.FileReader.<init>(FileReader.java:75)
[11:01:15 WARN]:        at AxGraves-1.14.0.jar//com.artillexstudios.axgraves.grave.SpawnedGraves.loadFromFile(SpawnedGraves.java:78)
[11:01:15 WARN]:        at AxGraves-1.14.0.jar//com.artillexstudios.axgraves.AxGraves.enable(AxGraves.java:55)
[11:01:15 WARN]:        at AxGraves-1.14.0.jar//com.artillexstudios.axgraves.libs.axapi.AxPlugin.onEnable(AxPlugin.java:111)
[11:01:15 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[11:01:15 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[11:01:15 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[11:01:15 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[11:01:15 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654)
[11:01:15 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603)
[11:01:15 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[11:01:15 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[11:01:15 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363)
[11:01:15 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[11:01:15 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[11:01:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by BenceX100** [comment]
Should be fixed in the latest version
