### ISSUE TITLE
java.io.FileNotFoundException: plugins/AxGraves/data.json (No such file or directory)

### ISSUE THREAD

**Issue by servicomcr** [Artillex-Studios/AxGraves#28]
[01:58:20 WARN]: java.io.FileNotFoundException: plugins/AxGraves/data.json (No such file or directory)
[01:58:20 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[01:58:20 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
[01:58:20 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
[01:58:20 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:179)
[01:58:20 WARN]:        at java.base/java.io.FileWriter.<init>(FileWriter.java:98)
[01:58:20 WARN]:        at AxGraves-1.14.3.jar//com.artillexstudios.axgraves.grave.SpawnedGraves.saveToFile(SpawnedGraves.java:68)
[01:58:20 WARN]:        at AxGraves-1.14.3.jar//com.artillexstudios.axgraves.schedulers.SaveGraves.lambda$start$0(SaveGraves.java:23)
[01:58:20 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[01:58:20 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[01:58:20 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[01:58:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[01:58:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[01:58:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by BenceX100** [comment]
I think this was fixed at some point, but feel free to reopen this if it still happens.
