### ISSUE TITLE
Graves not saving on server stop

### ISSUE THREAD

**Issue by PKGaspi** [Artillex-Studios/AxGraves#29]
Just testing this plugin. My desired configuration is unlimited time for graves (-1) and enable saving grave data when server is stopped and every 30 seconds. Nonetheless, the graves disappear when restarting the server.

Used version is 1.14.3 for mc 1.21.1 using spigot.

The following exception is thrown when stopping the server and there are graves in the world:

```
[21:54:17] [Server thread/ERROR]: Error occurred while disabling AxGraves v1.14.3 (Is it up to date?)
java.lang.NoSuchFieldError: Class org.bukkit.craftbukkit.v1_21_R1.util.CraftMagicNumbers does not have member field 'org.bukkit.UnsafeValues INSTANCE'
        at com.artillexstudios.axgraves.libs.axapi.nms.v1_21_R1.ItemStackSerializer.serializeAsBytes(ItemStackSerializer.java:27) ~[?:?]
        at com.artillexstudios.axgraves.libs.axapi.nms.v1_21_R1.items.WrappedItemStack.serialize(WrappedItemStack.java:62) ~[?:?]
        at com.artillexstudios.axgraves.libs.axapi.serializers.impl.ItemArraySerializer.serialize(ItemArraySerializer.java:29) ~[?:?]
        at com.artillexstudios.axgraves.libs.axapi.serializers.impl.ItemArraySerializer.serialize(ItemArraySerializer.java:14) ~[?:?]
        at com.artillexstudios.axgraves.grave.SpawnedGraves.saveToFile(SpawnedGraves.java:61) ~[?:?]
        at com.artillexstudios.axgraves.AxGraves.disable(AxGraves.java:74) ~[?:?]
        at com.artillexstudios.axgraves.libs.axapi.AxPlugin.onDisable(AxPlugin.java:157) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:269) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:513) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:505) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.disablePlugins(CraftServer.java:510) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4343-Spigot-a759b62-0a7bd6c]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:912) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4343-Spigot-a759b62-0a7bd6c]
        at net.minecraft.server.dedicated.DedicatedServer.v(DedicatedServer.java:716) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4343-Spigot-a759b62-0a7bd6c]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1107) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4343-Spigot-a759b62-0a7bd6c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4343-Spigot-a759b62-0a7bd6c]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by BenceX100** [comment]
Fixed in the latest version
