### ISSUE TITLE
Feature Request: 1.21.4 support / Issue: Error occurred while disabling AxGraves v1.16.0

### ISSUE THREAD

**Issue by LariOesch** [Artillex-Studios/AxGraves#37]
[12:27:40 INFO]: [AxGraves] Enabling AxGraves v1.16.0
[12:27:40 WARN]: [com.artillexstudios.axgraves.libs.axapi.nms.NMSHandlers] Could not load plugin AxGraves due to version mismatch! Found protocol version 769 which is unsupported!
[12:27:40 INFO]: [AxGraves] Disabling AxGraves v1.16.0
[12:27:40 ERROR]: Error occurred while disabling AxGraves v1.16.0
java.lang.NullPointerException: Cannot invoke "com.artillexstudios.axgraves.libs.axapi.config.Config.getBoolean(String, boolean)" because "com.artillexstudios.axgraves.AxGraves.CONFIG" is null
        at AxGraves-1.16.0 (1).jar/com.artillexstudios.axgraves.AxGraves.disable(AxGraves.java:75) ~[AxGraves-1.16.0 (1).jar:?]
        at AxGraves-1.16.0 (1).jar/com.artillexstudios.axgraves.libs.axapi.AxPlugin.onDisable(AxPlugin.java:133) ~[AxGraves-1.16.0 (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.4.jar:1.21.4-6-71a367e]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.4.jar:1.21.4-6-71a367e]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at AxGraves-1.16.0 (1).jar/com.artillexstudios.axgraves.libs.axapi.AxPlugin.onEnable(AxPlugin.java:40) ~[AxGraves-1.16.0 (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.4.jar:1.21.4-6-71a367e]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.4.jar:1.21.4-6-71a367e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.4.jar:1.21.4-6-71a367e]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.4.jar:1.21.4-6-71a367e]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:769) ~[paper-1.21.4.jar:1.21.4-6-71a367e]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:531) ~[paper-1.21.4.jar:1.21.4-6-71a367e]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.4.jar:1.21.4-6-71a367e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[paper-1.21.4.jar:1.21.4-6-71a367e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341) ~[paper-1.21.4.jar:1.21.4-6-71a367e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by AverageGithub** [comment]
[12:27:40 INFO]: [AxGraves] Enabling AxGraves v1.16.0
[12:27:40 WARN]: [com.artillexstudios.axgraves.libs.axapi.nms.NMSHandlers] Could not load plugin AxGraves due to version mismatch! Found protocol version 769 which is unsupported!

Meaninngg, 1.21.4 is not yet supported

**Comment by LariOesch** [comment]
> Meaninngg, 1.21.4 is not yet supported

Yeah, that's why it's titled as FR for 1.21.4 and as an issue.

_(This is also the last plugin that's not compatible with 1.21.4 on my server)_

**Comment by BenceX100** [comment]
The latest version should work with 1.21.4
